### ISSUE TITLE
Continue an existing chat

### ISSUE THREAD

**Issue by GridexX** [fyodorio/chat-with-yourself#1]
Hello @fyodorio !

I really like the idea of this project ! Just tried out and it help me a lot :smile: 

I have an idea of a feature, continue an existing chat.

It takes the markdown file as argument, it reads the name of the 2 persons and continue with the current-person. What do you think of this feature ? 

I would love to help with such a contribution :smile:

**Comment by fyodorio** [comment]
Hi @GridexX,

Thanks a lot for the nice words and sorry to hear that you got into the situation when you need this chat 😅

As for the idea you found, it sounds really cool to me, I'd say please go for this PR and let me know in case you need any support 👍

**Comment by Rouaa-Belhaj-Ali** [comment]
Hello @fyodorio  and @GridexX 

I really like  the concept of continuing a chat through a markdown file ; it truly adds a personalized and dynamic touch to interactions: i kinda thought about it . This idea sparked another thought – how about incorporating an "Auto-Personalization" feature? This addition could analyze the historical conversation between the individuals specified in the markdown file, dynamically adjusting the tone, language, and responses based on their past interactions. This way, the chat not only seamlessly continues but also reflects the unique communication style and preferences of each participant, making it feel more natural and tailored.

I'm genuinely interested in contributing to the development of this feature. Please let me know how I can get involved and help bring this idea to life. Your feedback on this extended feature would be highly appreciated!

**Comment by fyodorio** [comment]
Hi @Rouaa-Belhaj-Ali, thanks for your interest to the project.

Not sure what you mean here though. The `chat-with-yourself` is litterally a chat with yourself. Basically, only you can adjust the tone and language and responses (as they're _your_ responses)... Unless I missed some PRs to it already and it became an AI monster talking to you under the hood 😅

**Comment by Rouaa-Belhaj-Ali** [comment]
Hey @fyodorio ! 😄

I appreciate your response! I might have gotten a bit carried away with the idea of an "Auto-Personalization" feature in the chat-with-yourself project😅 . You're absolutely right it's all about chatting with oneself. No AI monsters lurking in the code...yet! 🤖

Your clarification makes perfect sense don't know what i was thinking 🤣, and I'm on board with the simplicity of enjoying a solo conversation. If any AI monsters decide to join the chat in the future, I'll make sure to send you a virtual monster-slayer kit! Thanks for keeping it real and fun!

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
camchis, @Pantyhose-X, @mordaha, @lemedro, @alberrrttt, @haroldo-ok, @bcgameProject, @LouisDuboscq, @Franceshe, @seandinwiddie, @deas, @shizhaojingszj, @jlangson, @krio, @DPS0340, @xinghunbuxiu, @voyager, @nathgilson, @mr-rohit, @mcchin, @trksb, @shamilovtim, @RyanKung, @ryanleecode, @tmeppp, @Astrabacus, @sebastian-palma, @watchworld, @kk2018, @truongvan2007, @sh3max, @nicodinh, @zhangtaii, @rencire, @mpangrazzi, @enerai, @ronaldlangeveld, @neoarma, @zhangpanrobot, @AeRo8, @WenHaiGo, @anarh1st47, @niranjan-h, @Kleak, @micahp, @jokalagary, @not-for-me, @arcanoix, @soaringfish, @nightznero

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
